baseURL = "https://manabisystem.com/"
languageCode = "ja"
title = "まなびシステム"
theme = "hugo-theme-simple-blog"
copyright = "© 2020 manabisystem.com."
paginate = 5
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-165312579-3"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
  posts = "/:slug"

[params]
  custom_css = ["css/custom.css"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "まなびシステムについて"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "contact"
    name = "お問い合わせ"
    url = "/contact/"
    weight = 11
